# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngram', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.TextField()),
                ('song_name', models.TextField()),
                ('lyrics', models.TextField()),
                ('filename', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='found_in',
            field=models.ManyToManyField(to='hhlookup.Song'),
        ),
    ]
