# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhlookup', '0004_auto_20170318_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='slug',
        ),
        migrations.AddField(
            model_name='song',
            name='artist_slug',
            field=models.TextField(default=''),
        ),
    ]
