# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhlookup', '0005_auto_20170419_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist_slug',
            new_name='slug',
        ),
    ]
