# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhlookup', '0006_auto_20170419_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='artist_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hhlookup.Artist'),
        ),
    ]
