# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 14:21
from __future__ import unicode_literals

from django.db import migrations

def link_artists(apps, schema_editor):
    Song = apps.get_model('hhlookup', 'Song')
    Artist = apps.get_model('hhlookup', 'Artist')
    for song in Song.objects.all():
        artist, created = Artist.objects.get_or_create(name=song.artist)
        song.artist_link = artist
        song.save()

class Migration(migrations.Migration):

    dependencies = [
        ('hhlookup', '0008_artists_to_fk'),
    ]

    operations = [
            migrations.RunPython(link_artists),
    ]
