# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhlookup', '0009_artists_to_fk_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.TextField(default=''),
        ),
    ]
