# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhlookup', '0010_artist_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='found_in_artist',
            field=models.ManyToManyField(null=True, to='hhlookup.Artist'),
        ),
    ]
