# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 18:11
from __future__ import unicode_literals

from django.db import migrations

def link_artists(apps, schema_editor):
    Match = apps.get_model('hhlookup', 'Match')
    Artist = apps.get_model('hhlookup', 'Artist')
    # For each match
    for match in Match.objects.all():
        # For each song in the match (we need the artist for each song)
        for song in match.found_in.all():
            artist = Artist.objects.get(name = song.artist)    
            match.found_in_artist.add(artist)
            
        match.save() 

class Migration(migrations.Migration):

    dependencies = [
        ('hhlookup', '0011_match_found_in_artist'),
    ]

    operations = [
            migrations.RunPython(link_artists),
    ]
